# Generated by Django 2.0.6 on 2018-11-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='phonecode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
