# Generated by Django 2.0.6 on 2018-11-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181112_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
