# Generated by Django 2.0.6 on 2018-11-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_applicationdocument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthdatehijri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='value',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In revision'), (3, 'In manager'), (4, 'In president'), (5, 'Returned'), (6, 'Rejected'), (7, 'Finished'), (8, 'On hold'), (9, 'Pending')], unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Renew')]),
        ),
    ]
