# Generated by Django 2.0.6 on 2018-11-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181113_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
