# Generated by Django 2.0.6 on 2018-11-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_applicant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='userid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='main.Applicant'),
        ),
    ]
