# Generated by Django 2.0.6 on 2018-11-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181113_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField(choices=[(1, 'Application'), (2, 'License')])),
            ],
        ),
        migrations.AddField(
            model_name='actionhistoryentry',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='value',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In revision'), (3, 'In manager'), (4, 'In president'), (5, 'Returned'), (6, 'Rejected'), (7, 'Finished'), (8, 'On hold'), (9, 'Pending payment')], unique=True),
        ),
        migrations.AddField(
            model_name='actionhistoryentry',
            name='target_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TargetType'),
        ),
    ]
