# Generated by Django 2.0.6 on 2018-11-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181115_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'PDF')], default=0),
        ),
    ]
