# Generated by Django 2.0.6 on 2018-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_applicationdocument_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
