# Generated by Django 2.0.6 on 2018-11-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_application_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='paid_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='value',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In revision'), (3, 'In manager'), (4, 'In president'), (5, 'Returned'), (6, 'Rejected'), (7, 'Finished'), (8, 'On hold'), (9, 'Pending payment'), (10, 'Returned to revision')], unique=True),
        ),
    ]
