# Generated by Django 2.0.6 on 2018-11-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181119_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='usertype',
            new_name='type',
        ),
    ]
