# Generated by Django 2.0.6 on 2018-11-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181125_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='commercial_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CommercialRecord'),
        ),
    ]
