# Generated by Django 2.0.6 on 2018-12-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_application_commercial_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LicenseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField(choices=[(1, 'Valid'), (2, 'Suspended')], unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ApplicantType',
            new_name='ApplicationType',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='type',
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ApplicationType'),
        ),
        migrations.AlterField(
            model_name='applicantcommercialrecord',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_crs', to='main.Applicant'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='value',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In revision'), (3, 'In manager'), (4, 'In president'), (5, 'Returned'), (6, 'Rejected'), (7, 'Finished'), (8, 'On hold'), (9, 'Pending payment'), (10, 'Returned to revision'), (11, 'Returned to manager'), (12, 'Pending payment approval'), (13, 'Pending payment returned'), (14, 'Payment approved')], unique=True),
        ),
        migrations.AddField(
            model_name='license',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='main.Application'),
        ),
        migrations.AddField(
            model_name='license',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.LicenseStatus'),
        ),
    ]
