# Generated by Django 2.0.6 on 2018-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181209_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='filepath',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='duration',
            field=models.IntegerField(choices=[(2, 'New'), (5, 'Renew')]),
        ),
    ]
