# Generated by Django 2.0.6 on 2018-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181212_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialrecord',
            name='activities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commercialrecord',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commercialrecord',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercialrecord',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='commercialrecord',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='commercialrecord',
            name='po_box',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='commercialrecord',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commercialrecord',
            name='zipcode',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
