data_cr_managers = [
  {
    "CR": 1010226682,
    "Name": "ياسر عبدالعزيز احمد المسعود",
    "NID": 1022901886,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير عام",
    "RelationTypeID": 20
  },
  {
    "CR": 1010228267,
    "Name": "سلطان عبدالله سليمان الراجحي",
    "NID": 1001673787,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير عام",
    "RelationTypeID": 20
  },
  {
    "CR": 1010228268,
    "Name": "محمد سعد مطلق ابوثنين",
    "NID": 1054613573,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير عام",
    "RelationTypeID": 20
  },
  {
    "CR": 1010002580,
    "Name": "عمر شعيان سعود العتيبي",
    "NID": 1029393293,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010002775,
    "Name": "محمـد سـليمان عبدالمحسـن أبانمـي",
    "NID": 1000108439,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010003188,
    "Name": "خالد سليمان مهنا المهنا",
    "NID": 1036130589,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010003528,
    "Name": "عبدالعزيز بن صـالح عبدالله آل الشـيخ",
    "NID": 1026503910,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010003633,
    "Name": "محمد ناهض العبدالعزيز الناهض",
    "NID": 1038770234,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010195178,
    "Name": "ابراهيم صالح عبدالله بن عسكر",
    "NID": 1012083877,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "نائب مدير",
    "RelationTypeID": 25
  },
  {
    "CR": 1010187817,
    "Name": "سعد عبدالمحسن عبدالمحسن السويلم",
    "NID": 1045460845,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير فرع",
    "RelationTypeID": 26
  },
  {
    "CR": 1010133194,
    "Name": "محمد عبدالله محمد سلمان  .",
    "NID": 1031228610,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير فرع",
    "RelationTypeID": 26
  },
  {
    "CR": 1010060622,
    "Name": "عبدالرحمن محمد عبدالرحمن بن عبيد",
    "NID": 1031375676,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير فرع",
    "RelationTypeID": 26
  },
  {
    "CR": 1010291696,
    "Name": "يوسف عبدالله عبدالعزيز الراجحي",
    "NID": 1029413869,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير فرع",
    "RelationTypeID": 26
  },
  {
    "CR": 1010291697,
    "Name": "يوسف عبدالله عبدالعزيز الراجحي",
    "NID": 1029413869,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير فرع",
    "RelationTypeID": 26
  },
  {
    "CR": 1010069202,
    "Name": "عبدالعزيز بن صـالح بن عبدالله آل الشـيخ",
    "NID": 1026503910,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير فرع",
    "RelationTypeID": 26
  },
  {
    "CR": 1010173173,
    "Name": "برناد نجم",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "الماني",
    "NationalityID": 36,
    "RelationType": "مدير عام",
    "RelationTypeID": 20
  },
  {
    "CR": 1010162642,
    "Name": "نسيب ابو خليل",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "الماني",
    "NationalityID": 36,
    "RelationType": "مدير عام",
    "RelationTypeID": 20
  },
  {
    "CR": 1010162642,
    "Name": "نجم برنارد",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "الماني",
    "NationalityID": 36,
    "RelationType": "مدير عام",
    "RelationTypeID": 20
  },
  {
    "CR": 1010162642,
    "Name": "حسام طلال امين غزاوي",
    "NID": 1028011805,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير عام",
    "RelationTypeID": 20
  },
  {
    "CR": 1010162642,
    "Name": "علي محمد الضميري (مدير تنفيذي)",
    "NID": 2007537604,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "أردني",
    "NationalityID": 106,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010302463,
    "Name": "دانيل جورج ستارتا جر ( مدير عام )",
    "NID": 218685875,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "أمـريكــي",
    "NationalityID": 92,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010302463,
    "Name": "جوهانيس  اوريك  ( عضو )",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "الماني",
    "NationalityID": 36,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010302463,
    "Name": "كريستين لورينز ( عضو )",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "الماني",
    "NationalityID": 36,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010267093,
    "Name": "حازم علي تعاريت",
    "NID": 2268599327,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "تونســي",
    "NationalityID": 88,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010162642,
    "Name": "طلال امين غزاوي (رئيس مجلس المديرين)",
    "NID": 1018250785,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010162642,
    "Name": "عدنان طلال غزاوي",
    "NID": 1018487007,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010162642,
    "Name": "ريسترك كيفن مارك",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "بريطـاني",
    "NationalityID": 12,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010027796,
    "Name": "محمد عبدالملك آل الشيخ(الرئيس )",
    "NID": 1001311693,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010027796,
    "Name": "رولف  ثورنكفيست",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سويديه",
    "NationalityID": 84,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010027796,
    "Name": "عبدالملك عبدالمحسن ال شيخ",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010027796,
    "Name": "محمد عبدالله الامام",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســوداني",
    "NationalityID": 82,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010042230,
    "Name": "عبد الله علي بن سالم الصاعدي",
    "NID": 1011331442,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010042230,
    "Name": "سلطان عبدالله علي الصاعدي",
    "NID": "",
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010042230,
    "Name": "تركي عبدالله علي الصاعدي",
    "NID": "",
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010205240,
    "Name": "طارق هاشم زكي النابلسي",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010205240,
    "Name": "هاني يعقوب كامل الحسيني",
    "NID": 105549939,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010208283,
    "Name": "عبدالله فهد عبدالله الجليفي",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010208283,
    "Name": "ايمان صالح علي العلاوي",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010245397,
    "Name": "نوفل معروف الدواليبي",
    "NID": 1000687028,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010245397,
    "Name": "فيصل نوفل الدواليبي",
    "NID": 1000687051,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010274808,
    "Name": "نــاصـــر بن مـحـمـد السـديـري",
    "NID": 1000581205,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010336606,
    "Name": "عبدالعزيز حمد ابراهيم السلوم",
    "NID": "",
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010359050,
    "Name": "عبدالله عبداللطيف حمد الجبر",
    "NID": 1003772249,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010410833,
    "Name": "عبدالرحمن عبدالله الجدعان(رئيس المجلس)",
    "NID": 1007765884,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010410833,
    "Name": "أحمد قيس عبدالفتاح(غيرتنفيذي)",
    "NID": 2102128408,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "كنــدى",
    "NationalityID": 16,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 1010410833,
    "Name": "لمياء عبدالعزيز البرغش",
    "NID": 1022894172,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 4030147843,
    "Name": "احمد حسن سعيد الجميع الغامدي",
    "NID": 1048692162,
    "Location": "جــــــدة",
    "LocationID": 4030,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  },
  {
    "CR": 4030151792,
    "Name": "الشريف موفق مشهور الحارث",
    "NID": 1011050083,
    "Location": "جــــــدة",
    "LocationID": 4030,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مدير",
    "RelationTypeID": 24
  }
]
