data_cr_ownerships = [
  {
    "CR": 1010314116,
    "Name": "فهد عاتق فهد آل سمره",
    "NID": 1034268670,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مالك المؤسسة",
    "RelationTypeID": 1
  },
  {
    "CR": 1010314117,
    "Name": "ماجد فتحي محمد اخضر",
    "NID": 1004199772,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مالك المؤسسة",
    "RelationTypeID": 1
  },
  {
    "CR": 1010314118,
    "Name": "فهد محمد عيضه الثبيتي",
    "NID": 1001088705,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مالك المؤسسة",
    "RelationTypeID": 1
  },
  {
    "CR": 1010314120,
    "Name": "هياء عبدالله مخلف المخلف",
    "NID": 1039300452,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "مالك المؤسسة",
    "RelationTypeID": 1
  },
  {
    "CR": 1010314121,
    "Name": "عبدالعزيز رسلان مهو السبيعي العنزي",
    "NID": 1039917792,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "مالك المؤسسة",
    "RelationTypeID": 1
  },
  {
    "CR": 1010006008,
    "Name": "بدر عبدالرحمن سليمان العلولا",
    "NID": 1070767346,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010040816,
    "Name": "شماء ابراهيم عبدالله الصغير",
    "NID": 1035752508,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010065855,
    "Name": "عبدالعزيز عبدالله محمد الحقيل",
    "NID": 1081874990,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010000154,
    "Name": "خالد عبدالله شيخ الصافي",
    "NID": 1024901843,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شريك متضامن",
    "RelationTypeID": 3
  },
  {
    "CR": 1010004233,
    "Name": "علي حمد ضعيان",
    "NID": 1029928866,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شريك متضامن",
    "RelationTypeID": 3
  },
  {
    "CR": 1010006039,
    "Name": "عبدالله بن حمد بن سليم",
    "NID": 1018485852,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شريك متضامن",
    "RelationTypeID": 3
  },
  {
    "CR": 1010002385,
    "Name": "حصه العبدالله الركماري",
    "NID": 1078238761,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "شريك موصى",
    "RelationTypeID": 4
  },
  {
    "CR": 1010004233,
    "Name": "امين حسن الضعيان",
    "NID": 1020615710,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شريك موصى",
    "RelationTypeID": 4
  },
  {
    "CR": 2050045491,
    "Name": "رشيد جمعان محمد الزهراني",
    "NID": 1027966041,
    "Location": "الدمـام",
    "LocationID": 2050,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شريك مؤسس",
    "RelationTypeID": 5
  },
  {
    "CR": 4030017038,
    "Name": "عبدالرحمن خالد عبدالله الدبل",
    "NID": 1001438983,
    "Location": "جــــــدة",
    "LocationID": 4030,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شريك مؤسس",
    "RelationTypeID": 5
  },
  {
    "CR": 1010027796,
    "Name": "عبدالمجسن عبدالملك ال شيخ",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010027796,
    "Name": "عبدالملك عبدالمحسن ال شيخ",
    "NID": 1009399021,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010042230,
    "Name": "عبد الله علي بن سالم الصاعدي",
    "NID": 1011331442,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010042230,
    "Name": "ماجد عبد الله علي الصاعدي",
    "NID": 1011331467,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010042230,
    "Name": "سلطان عبد الله علي الصاعدي",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010042230,
    "Name": "تركي عبدالله علي الصاعدي",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010042230,
    "Name": "محمد عبد الله علي الصاعدي",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010205240,
    "Name": "هاني يعقوب كامل الحسيني",
    "NID": "",
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010205240,
    "Name": "شركة توجيه الخدمات والاستثمارات التجارية",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010205240,
    "Name": "عبدالعزيز عبداللطيف بكر جزار",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010205240,
    "Name": "هاني ابراهيم بن انس الزبن",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010208283,
    "Name": "ايمان صالح علي العلاوي",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010208283,
    "Name": "عبدالله فهد عبدالله الجليفي",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010245397,
    "Name": "نوفل معروف الدواليبي",
    "NID": 1000687028,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010245397,
    "Name": "فيصل نوفل معروف الدواليبي",
    "NID": 1000687051,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010245397,
    "Name": "عدنان نوفل الدواليبي",
    "NID": 1000687044,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010245397,
    "Name": "عبدالرحمن فريد العظم",
    "NID": 1020650824,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010245397,
    "Name": "عبدالعزيز فريد العظم",
    "NID": 1020650832,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010245397,
    "Name": "سعيد فريد عبدالرحمن العظم",
    "NID": 1020650840,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010245397,
    "Name": "اسامه فريد عبد الرحمن العظم",
    "NID": 1070329220,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010274808,
    "Name": "ناصر محمد ناصر السديري",
    "NID": 1000581205,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010274808,
    "Name": "عبدالعزيز ناصر محمد السديري",
    "NID": 1110359930,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010336606,
    "Name": "شركة طريق الحلول للتجارة",
    "NID": "",
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010336606,
    "Name": "عبدالعزيز حمد ابراهيم السلوم",
    "NID": 1023508409,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010359050,
    "Name": "هشام عبداللطيف بن حمد الجبر",
    "NID": 1006798142,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010359050,
    "Name": "عبدالله عبداللطيف حمد الجبر",
    "NID": 1003772249,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010410833,
    "Name": "عبدالرحمن عبدالله الجدعان",
    "NID": 1007765884,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010410833,
    "Name": "لمياء عبدالعزيز عبدالرحمن البرغش",
    "NID": 1022894172,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 4030147843,
    "Name": "احمد حسن سعيد الجميع الغامدي",
    "NID": 1048692162,
    "Location": "جــــــدة",
    "LocationID": 4030,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 4030147843,
    "Name": "مريم مرجحاني سعيد الغامدي",
    "NID": 1017010974,
    "Location": "جــــــدة",
    "LocationID": 4030,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 4030151792,
    "Name": "الشريف موفق مشهور الحارث",
    "NID": 1011050083,
    "Location": "جــــــدة",
    "LocationID": 4030,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 4030151792,
    "Name": "الشركه العربيه للمشاريع الترفيهيه المحدوده",
    "NID": 4030131731,
    "Location": "جــــــدة",
    "LocationID": 4030,
    "Nationality": "سعـوديه",
    "NationalityID": 2,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010162642,
    "Name": "شركة بلال المحدوده",
    "NID": 2050005864,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "ســــعودى",
    "NationalityID": 1,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010162642,
    "Name": "شركة نوكيا سوليوشنز آند نتوبركس  سنغافورة بي تي أي ليمتد",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "فنلنديه",
    "NationalityID": 31,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010302463,
    "Name": "شركة ايه تي كيرني هولدينجز ليمتد",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "فنلنديه",
    "NationalityID": 31,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  },
  {
    "CR": 1010302463,
    "Name": "شركة ايه تي كيرني ليمتد",
    "NID": 0,
    "Location": "الريــاض",
    "LocationID": 1010,
    "Nationality": "فنلنديه",
    "NationalityID": 31,
    "RelationType": "شــريك",
    "RelationTypeID": 2
  }
]
