data_cr_data = [
  {
    "CRNo": 1010994569,
    "CRName": "مكتب عبدالمحسن سعد عبدالعزيز سعيد للعقارات",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 101,
    "CRNationalityName": "جزائرى",
    "IssueDate": 14370527,
    "ExpiryDate": 14420527,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 2050107530,
    "CRName": "مزرعة محمد عبدالله الخفره",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 2050,
    "CRLocationName": "الدمـام",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370221,
    "ExpiryDate": 14400220,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010542612,
    "CRName": "حلاق حامد محمد صالح دردير للحلاقة",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 101,
    "CRNationalityName": "جزائرى",
    "IssueDate": 14370119,
    "ExpiryDate": 14380119,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010440794,
    "CRName": "مؤسسة الصالحية للاتصالات وتقنية المعلومات",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 1,
    "CRNationalityName": "ســــعودى",
    "IssueDate": 14370401,
    "ExpiryDate": 14390401,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1011023968,
    "CRName": "مكتب النخلة الاهلية لتاجير السيارات",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1011,
    "CRLocationName": "الخــرج",
    "CRNationality": 1,
    "CRNationalityName": "ســــعودى",
    "IssueDate": 14370712,
    "ExpiryDate": 14380712,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010165177,
    "CRName": "مركز عوض علي القحطاني للبصريات",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 1,
    "CRNationalityName": "ســــعودى",
    "IssueDate": 14370312,
    "ExpiryDate": 14380312,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010297340,
    "CRName": "مؤسسة عبدالرحمن حمد السريع للتجارة",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 1,
    "CRNationalityName": "ســــعودى",
    "IssueDate": 14370106,
    "ExpiryDate": 14371203,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010318575,
    "CRName": "مؤسسة نافذة الموعد لتقنية المعلومات",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 101,
    "CRNationalityName": "جزائرى",
    "IssueDate": 14370713,
    "ExpiryDate": 14390713,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010438139,
    "CRName": "مؤسسة ظلال البحرين للتجارة",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 111,
    "CRNationalityName": "بحــريني",
    "IssueDate": 14370102,
    "ExpiryDate": 14420102,
    "IsMain": 1,
    "CRStatus": "SUSPENDED"
  },
  {
    "CRNo": 1010265273,
    "CRName": "موسسة ناي الرياض للدعاية والاعلان",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14430403,
    "ExpiryDate": 14350403,
    "IsMain": 0,
    "CRStatus": "EXPIRED"
  },
  {
    "CRNo": 1010298388,
    "CRName": "موسسه فهد عبود القحطاني للتجاره",
    "BusinessType": 101,
    "BusinessTypeName": "مؤســـسة فـــردية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 1,
    "CRNationalityName": "ســــعودى",
    "IssueDate": 14370102,
    "ExpiryDate": 14360102,
    "IsMain": 0,
    "CRStatus": "EXPIRED"
  },
  {
    "CRNo": 4031096223,
    "CRName": "فرع شركة مشاري ناصر الشثري وشريكه للاستشارات الهندسية",
    "BusinessType": 203,
    "BusinessTypeName": "تضــــــــامنية",
    "CRLocation": 4031,
    "CRLocationName": "مكه المكرمه",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370721,
    "ExpiryDate": 14380721,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 4030286888,
    "CRName": "فرع شركة المهندسون الاستشاريون ايه ايه دبليو وشركاه",
    "BusinessType": 203,
    "BusinessTypeName": "تضــــــــامنية",
    "CRLocation": 4030,
    "CRLocationName": "جــــــدة",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370318,
    "ExpiryDate": 14420318,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 4030285951,
    "CRName": "فرع شركة الخدمات الاستشاريةالسعودية للاستشارات الهندسية",
    "BusinessType": 203,
    "BusinessTypeName": "تضــــــــامنية",
    "CRLocation": 4030,
    "CRLocationName": "جــــــدة",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370206,
    "ExpiryDate": 14400206,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1122005573,
    "CRName": "فرع شركة عبدالجليل الفضلي واولاده للتجارة",
    "BusinessType": 201,
    "BusinessTypeName": "تــــوصية بســـيطة",
    "CRLocation": 1122,
    "CRLocationName": "المجمعه .",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370313,
    "ExpiryDate": 14390313,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1113003786,
    "CRName": "فرع شركة عمر صالح بابكر وشركاه للتموين",
    "BusinessType": 201,
    "BusinessTypeName": "تــــوصية بســـيطة",
    "CRLocation": 1113,
    "CRLocationName": "شقراء.",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370424,
    "ExpiryDate": 14390424,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 5850069293,
    "CRName": "فرع شركة محمد عبدالمحسن العبدالكريم وشركاه للتجارة",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 5850,
    "CRLocationName": "ابها",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370316,
    "ExpiryDate": 13110516,
    "IsMain": 0,
    "CRStatus": "EXPIRED"
  },
  {
    "CRNo": 2050108742,
    "CRName": "فرع شركة انتربلاست المحدودة",
    "BusinessType": 207,
    "BusinessTypeName": "فرع شركةأجنبيةمحدودة",
    "CRLocation": 2050,
    "CRLocationName": "الدمـام",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370606,
    "ExpiryDate": 14380606,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010442988,
    "CRName": "فرع شركة الموارد الزراعية المساهمه المحدوده",
    "BusinessType": 207,
    "BusinessTypeName": "فرع شركةأجنبيةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 606,
    "CRNationalityName": "أردنيه",
    "IssueDate": 14370618,
    "ExpiryDate": 14380113,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010442991,
    "CRName": "فرع شركة تيرميقاز بيرقامو اس بي ايه",
    "BusinessType": 207,
    "BusinessTypeName": "فرع شركةأجنبيةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 547,
    "CRNationalityName": "إيطاليه",
    "IssueDate": 14370613,
    "ExpiryDate": 14400618,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 5855069609,
    "CRName": "فرع شركة التقوى",
    "BusinessType": 205,
    "BusinessTypeName": "مســــــــــاهمة",
    "CRLocation": 5855,
    "CRLocationName": "خميس  مشيط",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370629,
    "ExpiryDate": 14420629,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010442918,
    "CRName": "فرع شركة الدريس للخدمات البترولية والنقليات",
    "BusinessType": 205,
    "BusinessTypeName": "مســــــــــاهمة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370614,
    "ExpiryDate": 14420614,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010438999,
    "CRName": "بترول الدريس  للخدمات",
    "BusinessType": 205,
    "BusinessTypeName": "مســــــــــاهمة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370129,
    "ExpiryDate": 14420129,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1013002264,
    "CRName": "فرع شركة الدريس للخدمات البترولية والنقليات",
    "BusinessType": 205,
    "BusinessTypeName": "مســــــــــاهمة",
    "CRLocation": 1013,
    "CRLocationName": "حوطه بني تميم",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370122,
    "ExpiryDate": 14420122,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": "",
    "CRName": "",
    "BusinessType": "",
    "BusinessTypeName": "",
    "CRLocation": "",
    "CRLocationName": "",
    "CRNationality": "",
    "CRNationalityName": "",
    "IssueDate": "",
    "ExpiryDate": "",
    "IsMain": "",
    "CRStatus": ""
  },
  {
    "CRNo": 1010027796,
    "CRName": "شركة الكترون السعوديه للخدمات",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14000226,
    "ExpiryDate": 14380530,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010042230,
    "CRName": "شركة اللواء للتجارة والمقاولات",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14020225,
    "ExpiryDate": 14410321,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010205240,
    "CRName": "شركه اجاده للنظم المحدوده",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14251226,
    "ExpiryDate": 14401226,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010208283,
    "CRName": "شركة مجموعة زاد المعلومات التجارية",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14260310,
    "ExpiryDate": 14410310,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010245397,
    "CRName": "شركه النهر للحلول الامنيه",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14290224,
    "ExpiryDate": 14390224,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010274808,
    "CRName": "الشركة الدولية للتعليم والتدريب المتقدم",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14301018,
    "ExpiryDate": 14401018,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010173173,
    "CRName": "شركه نوكيا سوليوشنز اند نيتوركس برانش اوبريشن او واي",
    "BusinessType": 207,
    "BusinessTypeName": "فرع شركةأجنبيةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 531,
    "CRNationalityName": "فنلنديـه",
    "IssueDate": 14221101,
    "ExpiryDate": 14391008,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010267093,
    "CRName": "فرع شركه اي ام جي اس جروب",
    "BusinessType": 207,
    "BusinessTypeName": "فرع شركةأجنبيةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 533,
    "CRNationalityName": "فرنسيـه",
    "IssueDate": 14300508,
    "ExpiryDate": 14371019,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010162642,
    "CRName": "شركة نوكيا سوليوشنز اند نتويركس  السعودية المحدودة",
    "BusinessType": 214,
    "BusinessTypeName": "ذات مسئولية محدودة مختلطة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14210809,
    "ExpiryDate": 14380217,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010302463,
    "CRName": "شركة ايه تي كيرني السعودية المحدودة",
    "BusinessType": 224,
    "BusinessTypeName": "محدودة أجنبية",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14320303,
    "ExpiryDate": 14380112,
    "IsMain": 1,
    "CRStatus": "SUSPENDED"
  },
  {
    "CRNo": 1010336606,
    "CRName": "شركة الاستشاريون المحترفون للتقنية",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14330602,
    "ExpiryDate": 14380602,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010359050,
    "CRName": "شركة فاز لتطوير الطاقة",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14340213,
    "ExpiryDate": 14390213,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010410833,
    "CRName": "شركة بيانات سدير للاتصالات وتقنية المعلومات",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14350615,
    "ExpiryDate": 14400615,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 1010441428,
    "CRName": "مركز ادوات الاحتراف للتدريب",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 1010,
    "CRLocationName": "الريــاض",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14370423,
    "ExpiryDate": 14380423,
    "IsMain": 0,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 4030151792,
    "CRName": "شركه المحترفون لتنميه الموارد البشريه ( معهد )",
    "BusinessType": 204,
    "BusinessTypeName": "ذات مسئوليةمحدودة",
    "CRLocation": 4030,
    "CRLocationName": "جــــــدة",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14250822,
    "ExpiryDate": 14400822,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  },
  {
    "CRNo": 4030147843,
    "CRName": "شركة المدارج العالميه للتسويق",
    "BusinessType": 205,
    "BusinessTypeName": "مســــــــــاهمة",
    "CRLocation": 4030,
    "CRLocationName": "جــــــدة",
    "CRNationality": 2,
    "CRNationalityName": "سعـوديه",
    "IssueDate": 14250123,
    "ExpiryDate": 14400122,
    "IsMain": 1,
    "CRStatus": "ACTIVE"
  }
]
